language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.1
    - php: 7.0.11
    - php: 5.6

sudo: false

install:
  - composer install

script:
  - phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
